DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/hpc2hdd/home/cliao127/MMSS-SAM-S1/sam/seg_exp/test' #mcubesiadn_lr0.0004batch4epoch500'      # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : CMNeXt                                            # name of the model you are using
  BACKBONE      : CMNeXt-B2                                         # model variant
  PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b4.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : MCubeS                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'data/multimodal_dataset'                # dataset root path
  IGNORE_LABEL  : 255
  #MODALS        : ['image'] # 
  MODALS        : ['image', 'aolp']
  # MODALS        : ['image', 'aolp', 'dolp']
  # MODALS        : ['image', 'aolp', 'dolp', 'nir']

TRAIN:
  IMAGE_SIZE    : [1024, 1024]      # training image size in (h, w) === Fixed in dataloader, following MCubeSNet
  BATCH_SIZE    : 4              # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_START    : 0             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in trainingcd 
  DDP           : true            # use DDP training

LOSS:
  NAME          : OhemCrossEntropy     # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw          # optimizer name
  LR            : 0.0004         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : '/hpc2hdd/home/cliao127/MMSS-SAM-Logs/Main/Mcubes/mcubes_ia_batch4epoch500lr0.00035/MCubeS_CMNeXt-B2_ia/epoch259_51.2.pth'
  # MODEL_PATH    : '/hpc2hdd/home/cliao127/MMSS-SAM-Logs/Main/Mcubes/mcubes_iad_batch4epoch500lr0.0004/MCubeS_CMNeXt-B2_iad/epoch326_52.2.pth'
  # MODEL_PATH    : '/hpc2hdd/home/cliao127/MMSS-SAM-Logs/Main/Mcubes/mcubesiadn_lr0.00035batch4epoch500/MCubeS_CMNeXt-B2_iadn/epoch453_52.88.pth'
  IMAGE_SIZE    : [1024, 1024]    # evaluation image size in (h, w)                       
  BATCH_SIZE    : 2               # batch size used to train
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
